export const theme = {
  colors: {
    background: '#F5F4F1',
    surface: '#FFFFFF',
    surfaceAlt: '#EEECEA',
    border: '#DDDBD5',
    borderStrong: '#1A1A1A',
    text: '#1A1A1A',
    textSecondary: '#7C7C7C',
    textTertiary: '#B8B6B0',
    accent: '#1A1A1A',
    accentLight: '#EEECEA',
    white: '#FFFFFF',
    black: '#000000',
    danger: '#C0392B',
    cityColors: {
      warszawa: '#1A1A1A',
      krakow: '#3D3530',
      wroclaw: '#2B3040',
      gdansk: '#1E3040',
      poznan: '#2E2820',
      lodz: '#302E2A',
      katowice: '#252525',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
  },
  radius: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 8,
    full: 999,
  },
  font: {
    sizes: {
      xs: 10,
      sm: 12,
      md: 14,
      lg: 16,
      xl: 20,
      xxl: 28,
      xxxl: 36,
      display: 48,
    },
    weights: {
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
      black: '900' as const,
    },
    letterSpacing: {
      tight: -0.5,
      normal: 0,
      wide: 1,
      wider: 2,
      widest: 3,
    },
  },
} as const;

export type Theme = typeof theme;
